"""Optional LanguageTool HTTP server child process for orateur run.

Starts a local, loopback-only LanguageTool server (https://dev.languagetool.org/http-server)
with a small JVM heap so it can sit in the background cheaply. Nothing in the speech
pipeline uses it yet — `check()` / `correct()` are here so STT output can be run through
it later.
"""

import json
import logging
import os
import shutil
import subprocess
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Optional

from .paths import CACHE_DIR, DATA_DIR

log = logging.getLogger(__name__)

DEFAULT_PORT = 8081
DEFAULT_MAX_HEAP = "256m"

# Generated on every start; keeps the server lean (one check thread, no caches).
SERVER_PROPERTIES = CACHE_DIR / "languagetool-server.properties"

_WRAPPER_NAMES = ("languagetool-http-server", "languagetool-server", "languagetool")

_JAR_CANDIDATES = (
    DATA_DIR / "languagetool" / "languagetool-server.jar",
    Path("/usr/share/languagetool/languagetool-server.jar"),
    Path("/usr/share/java/languagetool/languagetool-server.jar"),
    Path("/opt/languagetool/languagetool-server.jar"),
)


def base_url(config) -> str:
    """Base URL of the LanguageTool server (loopback only)."""
    port = int(config.get_setting("languagetool_port", DEFAULT_PORT) or DEFAULT_PORT)
    return f"http://127.0.0.1:{port}"


def is_server_running(config, *, timeout: float = 1.0) -> bool:
    """True if something answers the LanguageTool API on the configured port."""
    try:
        with urllib.request.urlopen(f"{base_url(config)}/v2/languages", timeout=timeout) as r:
            return r.status == 200
    except (urllib.error.URLError, OSError, ValueError):
        return False


def _find_jar(config) -> Optional[Path]:
    explicit = config.get_setting("languagetool_jar")
    if explicit:
        p = Path(explicit).expanduser()
        return p if p.is_file() else None
    home = os.environ.get("LANGUAGETOOL_HOME")
    candidates = list(_JAR_CANDIDATES)
    if home:
        candidates.insert(0, Path(home) / "languagetool-server.jar")
    for p in candidates:
        if p.is_file():
            return p
    # Unpacked LanguageTool-X.Y.zip in the data dir or home
    for parent in (DATA_DIR, Path.home()):
        try:
            for d in sorted(parent.glob("LanguageTool-*"), reverse=True):
                jar = d / "languagetool-server.jar"
                if jar.is_file():
                    return jar
        except OSError:
            continue
    return None


def _write_server_properties() -> Optional[Path]:
    """Minimal-footprint server config: single check thread, no caches."""
    try:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        SERVER_PROPERTIES.write_text(
            "# Generated by orateur — minimal LanguageTool server footprint.\n"
            "maxCheckThreads=1\n"
            "cacheSize=0\n"
            "pipelineCaching=false\n",
            encoding="utf-8",
        )
        return SERVER_PROPERTIES
    except OSError as e:
        log.debug("Could not write LanguageTool server properties: %s", e)
        return None


def _server_argv(config) -> Optional[tuple[list[str], dict[str, str]]]:
    """Command line + environment for the server, or None when LanguageTool is missing."""
    port = str(int(config.get_setting("languagetool_port", DEFAULT_PORT) or DEFAULT_PORT))
    heap = str(config.get_setting("languagetool_max_heap", DEFAULT_MAX_HEAP) or DEFAULT_MAX_HEAP)
    props = _write_server_properties()
    env = dict(os.environ)

    jar = _find_jar(config)
    if jar:
        argv = ["java", f"-Xmx{heap}", "-cp", str(jar), "org.languagetool.server.HTTPServer", "--port", port]
        if not shutil.which("java"):
            log.warning("Found %s but no `java` in PATH; install a JRE to use LanguageTool", jar)
            return None
    else:
        exe = next((shutil.which(n) for n in _WRAPPER_NAMES if shutil.which(n)), None)
        if not exe:
            return None
        argv = [exe, "--http", "--port", port]
        # The wrapper scripts build their own java command line; cap the heap via the JVM env.
        env["_JAVA_OPTIONS"] = f"-Xmx{heap}"
    if props:
        argv += ["--config", str(props)]
    return argv, env


def start_languagetool(config, *, wait_ready: float = 0.0) -> Optional[subprocess.Popen]:
    """Spawn the LanguageTool server detached from our stdin; None if unavailable or already up."""
    if is_server_running(config, timeout=0.5):
        log.info("LanguageTool already running at %s", base_url(config))
        return None
    resolved = _server_argv(config)
    if not resolved:
        log.warning(
            "LanguageTool not found — install it (e.g. the `languagetool` package) or set "
            "`languagetool_jar` in config.json to languagetool-server.jar"
        )
        return None
    argv, env = resolved
    try:
        proc = subprocess.Popen(
            argv,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            env=env,
            start_new_session=True,
        )
    except OSError as e:
        log.warning("Failed to start LanguageTool: %s", e)
        return None
    time.sleep(0.15)
    if proc.poll() is not None:
        log.warning("LanguageTool exited immediately (code %s)", proc.returncode)
        return None
    log.info("Started LanguageTool (pid %s) on %s", proc.pid, base_url(config))

    if wait_ready > 0:
        deadline = time.monotonic() + wait_ready
        while time.monotonic() < deadline:
            if proc.poll() is not None:
                log.warning("LanguageTool exited while starting (code %s)", proc.returncode)
                return None
            if is_server_running(config, timeout=0.5):
                log.info("LanguageTool ready")
                return proc
            time.sleep(0.3)
        log.warning("LanguageTool did not answer within %.0fs (still starting?)", wait_ready)
    return proc


def stop_languagetool(proc: Optional[subprocess.Popen], *, timeout: float = 5.0) -> None:
    if proc is None or proc.poll() is not None:
        return
    try:
        proc.terminate()
    except OSError:
        return
    try:
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        try:
            proc.kill()
        except OSError:
            pass


def check(text: str, config, *, language: Optional[str] = None, timeout: float = 10.0) -> Optional[dict[str, Any]]:
    """POST text to /v2/check. Returns the parsed response, or None if the server is unreachable."""
    lang = language or config.get_setting("languagetool_language", "auto") or "auto"
    data = urllib.parse.urlencode({"language": lang, "text": text}).encode("utf-8")
    req = urllib.request.Request(
        f"{base_url(config)}/v2/check",
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read().decode("utf-8"))
    except (urllib.error.URLError, OSError, ValueError) as e:
        log.warning("LanguageTool check failed: %s", e)
        return None


def correct(text: str, config, *, language: Optional[str] = None, timeout: float = 10.0) -> str:
    """Apply the first suggestion of every match. Returns `text` unchanged on any failure."""
    result = check(text, config, language=language, timeout=timeout)
    if not result:
        return text
    matches = result.get("matches") or []
    # Apply from the end so earlier offsets stay valid.
    out = text
    for m in sorted(matches, key=lambda m: m.get("offset", 0), reverse=True):
        replacements = m.get("replacements") or []
        if not replacements:
            continue
        value = replacements[0].get("value")
        if value is None:
            continue
        offset, length = m.get("offset", 0), m.get("length", 0)
        out = out[:offset] + value + out[offset + length :]
    return out
